# Generated by Django 5.0.3 on 2024-07-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_address_alter_item_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='spouse_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
